jenkins-x/jenkins-x-builders

- builder-python37/Dockerfile
- jx-docker-build.sh
Add support for Python 3.7 builder
> Add Python 3.7.1 builder

- builder-go/Dockerfile
Avoids `go.sum` checksum issues
> feat: upgrade to go 1.11.4

- builder-maven-nodejs/Dockerfile
- jx-docker-build.sh
@jstrachan Added Maven+NodeJS builder as agreed in https://kubernetes.slack.com/messages/C9LTHT2BB/convo/C9LTHT2BB-1545398900.027000/ .
> Added Maven+NodeJS image

- .gitignore
Added Git ignore for people editing Dockerfiles in IntelliJ for syntax highlighting (like myself).
> Added IntelliJ to Git ignore

- builder-gradle4/Dockerfile
- builder-gradle4/set_java
- builder-gradle5/Dockerfile
- builder-gradle5/set_java
- builder-nodejs10x/Dockerfile
- builder-nodejs8x/Dockerfile
- jx-docker-build.sh
Hi @jstrachan, here are the images as discussed in [ the jenkins-x-dev chat](https://kubernetes.slack.com/archives/C9LTHT2BB/p1546509821067900)
> Add new version specific gradle and nodejs images

- builder-base/build.sh
- jx-docker-build.sh
> feat(latest) attempting to push :latest on release build

- builder-maven-java11/Dockerfile
- upgraded base image
- upgraded Java version
- locked Java version number
> Upgraded base image and JDK for Java 11

- builder-aws-cdk/Dockerfile
- jx-docker-build.sh
I've added AWS CDK builder image. This is the first steps towards adding AWS CDK (https://github.com/awslabs/aws-cdk) buildpack support for Jenkins X.
> Added AWS CDK builder image

- builder-awscli-local/Dockerfile
- builder-awscli-local/skaffold.yaml
- builder-awscli/Dockerfile
- builder-awscli/skaffold.yaml
Created two new builder images based on the python37 builder image.  One of them installs the AWS CLI, the other installs the awscli-local package.
> Created builder images for awscli and awscli-local

- builder-dlang/Dockerfile
- builder-dotnet/Dockerfile
- builder-go-maven/Dockerfile
- builder-go/Dockerfile
- builder-gradle/Dockerfile
- builder-gradle4/Dockerfile
- builder-gradle5/Dockerfile
- builder-jx/Dockerfile
- builder-maven-32/Dockerfile
- builder-maven-java11/Dockerfile
- builder-maven/Dockerfile
- builder-newman/Dockerfile
- builder-nodejs/Dockerfile
- builder-nodejs10x/Dockerfile
- builder-nodejs8x/Dockerfile
- builder-python/Dockerfile
- builder-python2/Dockerfile
- builder-python37/Dockerfile
- builder-ruby/Dockerfile
- builder-rust/Dockerfile
- builder-scala/Dockerfile
- builder-swift/Dockerfile
- builder-terraform/Dockerfile
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed docker dependency: `JX_VERSION` to: `1.3.992`
> update JX_VERSION to 1.3.992

- builder-machine-learning/Dockerfile
- update-bot.sh
I have revised this to incorporate the basic features necessary to support portable ML models and added the relevant hook to update-bot.
> Updates to Machine Learning builder

- builder-go/Dockerfile
Signed-off-by: Pete Muir <pmuir@bleepbleep.org.uk>
> feat: add gotestsumn to builder-go

- builder-machine-learning-gpu/Dockerfile
- builder-machine-learning-gpu/test/container-test.yaml
- jenkins-x.yml
- update-bot.sh
Signed-off-by: Terry Cox <terry@bootstrap.je>
> feat: Add builder for training Machine Learning projects using CUDA

- builder-machine-learning-gpu/Dockerfile
Signed-off-by: Terry Cox <terry@bootstrap.je>
> chore: Update dependencies to include pytorch 1.1.0 and onnx 1.5.0

- update-bot.sh
Update the version of builder-jx in jenkins-x-platform
> fix: Update builder-jx in jenkins-x-platform

- jenkins-x.yml
> chore: add memory request/limits

- update-bot.sh
This doesn't actually do anything
> chore: remove chart pr for env controller

- Dockerfile.gobase
- Dockerfile.mavenbase
- builder-go-maven/Dockerfile
- builder-gradle/Dockerfile
- builder-gradle4/Dockerfile
- builder-gradle5-java11/Dockerfile
- builder-gradle5/Dockerfile
- builder-maven-32/Dockerfile
- builder-maven/Dockerfile
- builder-nodejs10x/Dockerfile
- builder-nodejs12x/Dockerfile
- builder-php5x/Dockerfile
- builder-php7x/Dockerfile
- builder-python/Dockerfile
- builder-python37/Dockerfile
- builder-rust/Dockerfile
- builder-scala/Dockerfile
> chore: Clean up dangling downloads/cache/etc in a few places

- OWNERS
- update-bot.sh
> fix: Wrong path for jx in updatebot.sh

- update-bot.sh
> fix: Specify jx.git as source for jx version updates downstream

- builder-terraform/Dockerfile
Use latest patch releases of both tools.
> chore(deps): bump Terraform and Terragrunt versions

- builder-go-nodejs/Dockerfile
- jenkins-x.yml
- replace-versions.sh
- update-bot.sh
> chore: Add `builder-go-nodejs` for UI tests in BDD tests

- update-bot.sh
> chore: Add builder-dotnet to updatebot

- Dockerfile.gobase
- Dockerfile.mavenbase
- builder-go-maven/Dockerfile
- builder-maven-32/Dockerfile
- builder-maven-graalvm/Dockerfile
- builder-maven/Dockerfile
See https://groups.google.com/forum/m/#!msg/golang-announce/Hsw4mHYc470/WJeW5wguEgAJ
> fix: Update golang version

- builder-maven-graalvm/Dockerfile
Signed-off-by: Svilen Valkanov <svilen.valkanov@home-ix.com>
> feat: Update Graal version to 19.3.1(java11) and update download URL

- jenkins-x.yml
We may have been getting bit by a bug on the latest warmer image, so let's do this instead.
> chore: Pin warmer image tag

- update-bot.sh
corrected the one that is still used
> chore: remove unused updatebot PRs to arcalos repo

- builder-scala/Dockerfile
release notes:
https://github.com/sbt/sbt/releases
> chore(deps): bump sbt to 1.3.10

- Dockerfile.gobase
> chore: Switch from go 1.12.16 to 1.13.8.

- builder-newman/Dockerfile
> fix: Update node to 10.x

- jenkins-x.yml
> fix: Fix input parameters for Tekton 0.11

- builder-terraform/Dockerfile
- builder-terraform/test/container-test.yaml
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>
> chore: update tf version and remove terragrunt
