jenkins-x/jenkins-x-builders

builder-newman/Dockerfile, builder-newman/README.md, jx-docker-build.sh
Addition of a newman builder. Newman is a command-line tool for running Postman Collections. The newman builder image will be useful for executing acceptance tests against preview environments.
The jx-docker-build.sh script was modified to support builder images that depend on builder images other than builder-base.
=> Add newman builder

builder-go/Dockerfile
Several of us now have go 1.11.2 locally and it seems to cause problems with the modules hashes (https://github.com/golang/go/issues/27925). Would be great to align on the latest available.
=> Update go to 1.11.2

builder-base/Dockerfile.common
Now that we are using helm >= 2.11, tiller is included in the release, so we can use the same version for both binaries.
This fixes the following error when using helm with a local tiller:
```
incompatible versions client[v2.12.2] server[v2.10.0]
```
=> fix(helm): use the right tiller version

builder-go/Dockerfile
This PR adds `dep` to the builder-go image.
=> Add dep as dependency manager

builder-newman/Dockerfile
The newman builder image installs a lot of packages that are not needed to run newman.  This PR removes them and adds a line to print the version of newman to verify its installation.
=> Removed unnecessary packages from newman builder image dockerfile.

jenkins-x.yml
Nodejs10x currently points to Nodejs8x
=> Fix typo for nodejs10x docker image

builder-terraform/Dockerfile
You must use Terragrunt `0.19` and above with Terraform `0.12`. There are breaking changes to Terragrunt `0.19`, see their [docs for details](https://github.com/gruntwork-io/terragrunt/blob/master/_docs/migration_guides/upgrading_to_terragrunt_0.19.x.md).
=> Upgrade Terragrunt to 0.19.4

jenkins-x.yml, update-bot.sh
They just take too long and there's reason to believe they're so big
that they're causing issues with Kaniko. Some discussion in
https://github.com/jenkins-x/jx/issues/4671, but yeah, we need to find
a better way to build them. For now, this will leave the existing
images in place for the time being.
=> chore: Disabling building and updating of ML builders for now.

jenkins-x.yml, update-bot.sh
Also fixed the tag for `nodejs10x`, which was pushing on release to `nodejs8x`. Oops.
Relates to https://github.com/jenkins-x/jx/issues/4771, depends on https://github.com/jenkins-x/jx/pull/4777, which will be in the relevant builder starting with https://github.com/jenkins-x/jenkins-x-builders/pull/582
/assign @pmuir 
/assign @warrenbailey
=> fix: One `jx step create pr chart` call for all of jenkins-x-platform

jenkins-x.yml
For the PR build, we don't need to share workspace state before/after
the builders themselves, so it should be more easily parallelizable.
=> feat: Run just the PR build in parallel

jenkins-x.yml
This will get around image backoff annoyances due to these steps using
images we built earlier.
=> fix: Move updatebot and release notes into a separate stage

jenkins-x.yml
Hopefully maybe possibly this will help cut down on cases of Kaniko plus giant layers running in multiple pods on a single node causing the node to flop over due to `ContainerGCFailed` errors. Still not sure exactly what's causing that - talking with Kaniko people, the error is likely caused by resource contention, and perhaps could be ameliorated with a newer docker version on the nodes, but no one's quite sure. Anyway, this will hopefully help some.
/assign @rawlingsj 
/assign @garethjevans
=> chore: Cut down parallelism, try to get them to run on different nodes

Dockerfile.gobase
Switched to compiling Hugo as Centos 7 doesn't have GLIBCXX versions the pre-combiled binary relies on
=> chore: bumped Hugo from 0.49 to 0.58.0/extended

builder-gradle/Dockerfile, builder-gradle4/Dockerfile, builder-gradle5/Dockerfile, jenkins-x.yml, update-bot.sh
Note that this will _not_ work without metapipeline enabled, since it needs `${BUILD_NUMBER}` available. I'm also not 100% sure it'll work at all, but I'm...99% sure?
EDIT: Also started handling https://github.com/jenkins-x/jx/issues/5596 here by updating the JX version in `jenkins-x-platform` and `prow` charts from here. We'll still need to turn off the update in JX. Opening a PR for that.
Also splits to five parallel batches of 6 images per batch (except for one with 5), and reorganizes the builders by batch to stack builders with common layers in the same batch, along with making gradle builders share a common layer.
/assign @cagiti 
fixes https://github.com/jenkins-x/jx/issues/5595
part of https://github.com/jenkins-x/jx/issues/5596
=> fix: Use jx version as basis for release version

builder-maven-graalvm/Dockerfile
Updated Graal to the current version: 19.2.1
Added native image build tools to enable native builds with this builder
Note: "Traditional" builds are still possible
=> feat: Updated graal to current version, added native-image build tools

jenkins-x.yml
So let's run it on a go-maven builder just to be safe in case there
actually is something that needs maven too.
=> fix: update-bot.sh execution needs go now

builder-python37/Dockerfile
The current version of builder-python37 is compiled with SQLite3 support:
```bash
➜  builder-python37 git:(master) docker run -it  gcr.io/jenkinsxio/builder-python37 /bin/bashUnable to find image 'gcr.io/jenkinsxio/builder-python37:latest' locally
latest: Pulling from jenkinsxio/builder-python37
Digest: sha256:83ca593cf76e66de6b4eed4d7030eaf95023172f781c04bbca8369e8ddedefb6
Status: Downloaded newer image for gcr.io/jenkinsxio/builder-python37:latest
[root@805a59668c29 jenkins]# python3
Python 3.7.1 (default, Dec 10 2019, 12:38:12)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.7/sqlite3/__init__.py", …
```
=> fix: build python37 with SQLite3 support

builder-terraform/Dockerfile
In Terraform 0.12.17 they added the trim* functions. I need them for the EKS module.
=> feat: increase Terraform version to 0.12.17

builder-maven-graalvm/Dockerfile
We're already quite well into 2020, we might want to update to the 20.20 release of GraalVM.
I'm oke with waiting till there's more than a .0.0 release, but otherwise, this should work fine.
Signed-off-by: Joost van der Griendt <joostvdg@gmail.com>
=> chore: bump graalvm version to 20.0.0

builder-maven-graalvm-java11/Dockerfile, jenkins-x.yml, update-bot.sh
Now that GraalVM + Maven works well with Java 11, it would be good to support this out of the box.
Signed-off-by: Joost van der Griendt <joostvdg@gmail.com>
=> chore: add maven graalvm builder for java 11
